### ISSUE TITLE
Initial set up errors

### ISSUE THREAD

**Issue by mtourtellott** [kevinwojo/hubzero-vagrant#1]
When completing steps:

---

==> default:  On the HOST:
==> default:  Go to the public directory: 
==> default:  Run: git clone http://github.com/hubzero/hubzero-cms
==> default:  Then run: git checkout 2.0.0
==> default:  Then cp -r /var/www/app-scotch /var/www/public/app
==> default: 

---

Error in browser when testing it: http://hubzero.local/hubzero-cms/

Warning: require(/var/www/public/hubzero-cms/core/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/public/hubzero-cms/core/bootstrap/autoload.php on line 21

Fatal error: require(): Failed opening required '/var/www/public/hubzero-cms/core/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/public/hubzero-cms/core/bootstrap/autoload.php on line 21

**Comment by kevinwojo** [comment]
You'll need to `git checkout 2.0.0`.

So this occurs when you are on the master branch, as when we are developing on master we use https://github.com/hubzero/framework in that location. I think you can play around with Composer to bring it in, usually my work in the framework is short-lived and I just clone it into core/vendor/hubzero/ resulting in core/vendor/hubzero/framework. In 2.0.0 this is actually converted to core/libraries/Hubzero as it's kind of a snapshot of development when we drew the line in the sand for that version release.

None-the-less I might do have a typo in the git clone step. Should read `git clone https://github.com/hubzero/hubzero-cms ./`

**Comment by kevinwojo** [comment]
closed with 1c030121d31a0ebc581fd0dc06f7b3516484833c
