### ISSUE TITLE
Confused on setup

### ISSUE THREAD

**Issue by mdlama** [kevinwojo/hubzero-vagrant#2]
Hi, Kevin!  This vagrant box is much appreciated.  I've tried getting the VMs setup for some students over here at William and Mary and had some trouble getting their machines to work through Virtual Box.  Here's to hoping this solves the issue.

However, I am confused about steps to get this up and running.  When you say "Host", do you mean my laptop, for example?  That's what I thought, given that you said NOT the "vagrant ssh" environment.  If this is the case, why in the world would I put hubzero-cms into my laptops /var/www/public directory?  Shouldn't hubzero-cms be installed in the "vagrant ssh" environment?

Hopelessly confused,

Drew

**Comment by kevinwojo** [comment]
Hi Drew, I've went ahead and corrected the README file with the correct instructions. You're correct in that you should do this within the `vagrant ssh` environment. Closing with e7c8b163b30aea1e4b558a0b107901bd8a5138e6.

**Comment by mdlama** [comment]
Awesome, thanks, Kevin!
