### ISSUE TITLE
Minor issues with setup

### ISSUE THREAD

**Issue by mdlama** [kevinwojo/hubzero-vagrant#3]
Hi, Kevin.  It worked!  Thanks for updating the README.  Couple of things:
1.  https didn't work for me with the "git clone" command (timed out).  I had to use http to make it work.
2.  When removing the app directory, I had to add "-rf" to the rm command.

Other than that, I'm up and running!
- Drew

**Comment by kevinwojo** [comment]
Did this ever get resolved?

**Comment by mdlama** [comment]
Yep!  Closing down...
