### ISSUE TITLE
Having trouble getting setup again

### ISSUE THREAD

**Issue by mdlama** [kevinwojo/hubzero-vagrant#4]
Hi, Kevin!  I'm getting back into working with students on web development and tried getting a new vagrant box setup on one of my computers.  I ran into trouble, however.  Here are my steps:
1.  Download and install Vagrant.
2.  Download and install VirtualBox.
3.  Clone kevinwojo/hubzero-vagrant (https://github.com/kevinwojo/hubzero-vagrant.git) onto my machine.
4.  Run `vagrant up`.
5.  Run `vagrant ssh`.
6.  From within `/var/www/public` on the VM:
   - `git clone http://github.org/hubzero/hubzero-cms ./` 
   - `git config core.fileMode false`
   - `git checkout 2.1.0 -f` (updated directions for 2.1)
   - Remove the existing app directory: `rm -rf /var/www/public/app`
   - `cp -r /var/www/app-scotch /var/www/public/app`

I am then unable to login to `https://192.168.33.10/administrator` on my machine (I get ERR_CONNECTION_REFUSED).  I can ping it and it is up and responsive, and I checked `ifconfig` on the VM and the IP is correct.  Any thoughts?

**Comment by kevinwojo** [comment]
Ah yes, try:
1. Download and install Vagrant.
2. Download and install VirtualBox.
3. Clone kevinwojo/hubzero-vagrant (https://github.com/kevinwojo/hubzero-vagrant.git) onto my machine.
4. Run vagrant up.
5. Run vagrant ssh.
6. From within /var/www/public on the VM:
7. git clone http://github.org/hubzero/hubzero-cms ./
8. git config core.fileMode false
9. git checkout 2.1.0 -f (updated directions for 2.1)
10. Remove the existing app directory: rm -rf /var/www/public/app
11. cp -r /var/www/app-scotch /var/www/public/app
12. `cd core && ./bin/composer install && cd ../`
13. `./muse migration -i -f`

The last bit composer install is a new thing as of 2.1.0 - it pulls in the framework and other PHP dependencies. 

You'll also have to access the invalid certificate.

**Comment by kevinwojo** [comment]
b05ab3b41c7a138b3e27ed2ff7758149da447bdc
